<script type="text/javascript">
	function addHidden(id){
		var tot = parseInt($("#n"+id).val());
		tot = tot + 1;
		$("#n"+id).val(tot);
		$("#d"+id).val(tot); 
	};

	function remHidden(id){
		var tot = parseInt($("#n"+id).val());
		if(tot <= 0){
			tot = 0;
		}else{
			tot = tot - 1;
		}
		$("#n"+id).val(tot);
		$("#d"+id).val(tot); 
	};

	$(document).ready(function() {
		$('#tordenes').DataTable({
			"aaSorting": [[ 0, "desc" ]]
			});	
		$('#plus').hide();

		var counter = 60;
		var timer = function(){
			$('div.counter').html("La p&aacute;gina se recargar&aacute; en " +counter + " segundos");
			  if(counter == 0){
				  //alert("termino counter");
				  this.document.location.href = "/cafeteria/orden/cocina";
			  }
			  counter--;
			  setTimeout(timer,1000);
			};
		timer();	
	} );

	function hideForm() {
		$("#hform").hide();
		$("#plus").show();
	}

	function showForm() {
		$("#plus").hide();
		$("#hform").show();
	}
</script>
<link rel="stylesheet" type="text/css" href="css/cocina.css">
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form; 
echo $this->view->tabla;
?>
<div id="counter" name="counter" class="counter"></div>
