<?php
echo $this->getContent();
?>

<div class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <?php
                echo $this->view->prodLeft;
                ?>
            </div> <!-- /.col-md-3 -->
            <div class="col-md-5">
                <div class="product-holder">
                    <div class="product-item-2">
                        <?php
                        echo $this->view->prodCenter1;
                        ?>
                    </div> <!-- /.product-item-2 -->
                    <div class="product-item-2">
                        <?php
                        echo $this->view->prodCenter2;
                        ?>
                    </div> <!-- /.product-item-2 -->
                    <div class="clearfix"></div>
                </div> <!-- /.product-holder -->
            </div> <!-- /.col-md-5 -->
            <div class="col-md-4">
                <div class="product-item-3">
                    <?php
                    echo $this->view->prodRight;
                    ?>
                </div> <!-- /.product-item-3 -->
            </div> <!-- /.col-md-4 -->
        </div> <!-- /.row -->
    </div>
</div>

<div class="content-section">
    <div class="container">
        <div class="row">
            <?php
            echo $this->view->prodThumb1;
            echo $this->view->prodThumb2;
            echo $this->view->prodThumb3;
            ?>
        </div> <!-- /.row -->
    </div>
</div>
        
<div class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 section-title">
                <h2>Nuevos Productos</h2>
            </div> <!-- /.section -->
        </div> <!-- /.row -->
        <div class="row">
            <?php
            echo $this->view->newProd;
            ?>
        </div> <!-- /.row -->
    </div>
</div>
<?php 
/*
<div class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 section-title">
                <h2>Vote For Future Products</h2>
            </div> <!-- /.section -->
        </div> <!-- /.row -->
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="product-item-vote">
                    <div class="product-thumb">
                        <img src="images/products/1.jpg" alt="">
                    </div> <!-- /.product-thum -->
                    <div class="product-content">
                        <h5><a href="#">Name of Shirt</a></h5>
                        <span class="tagline">By: Catherine</span>
                        <ul class="progess-bars">
                            <li>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                                    <span>4<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                            <li>
                                <div class="progress">
                                    <div class="progress-bar comments" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                    <span class="comments">6<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                        </ul>
                    </div> <!-- /.product-content -->
                </div> <!-- /.product-item-vote -->
            </div> <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <div class="product-item-vote">
                    <div class="product-thumb">
                        <img src="images/products/2.jpg" alt="">
                    </div> <!-- /.product-thum -->
                    <div class="product-content">
                        <h5><a href="#">Name of Shirt</a></h5>
                        <span class="tagline">By: Rebecca</span>
                        <ul class="progess-bars">
                            <li>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                                    <span>4<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                            <li>
                                <div class="progress">
                                    <div class="progress-bar comments" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                    <span class="comments">6<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                        </ul>
                    </div> <!-- /.product-content -->
                </div> <!-- /.product-item-vote -->
            </div> <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <div class="product-item-vote">
                    <div class="product-thumb">
                        <img src="images/products/3.jpg" alt="">
                    </div> <!-- /.product-thum -->
                    <div class="product-content">
                        <h5><a href="#">Name of Shirt</a></h5>
                        <span class="tagline">By: Catherine</span>
                        <ul class="progess-bars">
                            <li>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                                    <span>4<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                            <li>
                                <div class="progress">
                                    <div class="progress-bar comments" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                    <span class="comments">6<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                        </ul>
                    </div> <!-- /.product-content -->
                </div> <!-- /.product-item-vote -->
            </div> <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <div class="product-item-vote">
                    <div class="product-thumb">
                        <img src="images/products/4.jpg" alt="">
                    </div> <!-- /.product-thum -->
                    <div class="product-content">
                        <h5><a href="#">Name of Shirt</a></h5>
                        <span class="tagline">By: Rebecca</span>
                        <ul class="progess-bars">
                            <li>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                                    <span>4<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                            <li>
                                <div class="progress">
                                    <div class="progress-bar comments" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                    <span class="comments">6<i class="fa fa-heart"></i></span>
                                </div>
                            </li>
                        </ul>
                    </div> <!-- /.product-content -->
                </div> <!-- /.product-item-vote -->
            </div> <!-- /.col-md-3 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</div> <!-- /.content-section -->
 */
?>