<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Online Mall</title>
        <base href="/tienda/">
        
        <link rel="stylesheet" type="text/css" href="css/jquery-ui.css">
        <link href="https://cdn.jsdelivr.net/npm/vanilla-datatables@latest/dist/vanilla-dataTables.min.css" rel="stylesheet" type="text/css">
        
        <!-- template files 
        css/jquery.dataTables.min.css
        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
        
        Reemplazan a:
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'>
        
        <link rel="stylesheet" href="css/reset.css">
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
        <link rel="stylesheet" type="text/css" href="css/w3.css">
        <link rel="stylesheet" type="text/css" href="css/classic.css">
        <link rel="stylesheet" type="text/css" href="css/classic.date.css">
        <link rel="stylesheet" type="text/css" href="css/otros.css">
        
        -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet">

        <link rel="stylesheet" href="css/bootstrap.css">
        <link rel="stylesheet" href="css/normalize.min.css">
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="css/animate.css">
        <link rel="stylesheet" href="css/templatemo-misc.css">
        <link rel="stylesheet" href="css/templatemo-style.css">

        <script src="js/vendor/modernizr-2.6.2.min.js"></script>        
        <script src="https://cdn.jsdelivr.net/npm/vanilla-datatables@latest/dist/vanilla-dataTables.min.js" type="text/javascript"></script>
        
        <!-- Favicon 
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
		<link rel="icon" href="images/favicon.ico" type="image/x-icon">
		<link rel="apple-touch-icon" sizes="57x57" href="image/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="image/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="image/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="image/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="image/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="image/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="image/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="image/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="image/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="image/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="image/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="image/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="image/favicon-16x16.png">
		<link rel="manifest" href="image/manifest.json">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="image/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">
		-->

        
        
        <!-- Latest compiled and minified JavaScript 
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        -->
        
        
        
        <!-- reducir elementos de javascript
        
        <script src="https://use.fontawesome.com/b88a17f1bf.js"></script>
        
        <script src="https://npmcdn.com/react@15.3.0/dist/react.min.js"></script>
		<script src="https://npmcdn.com/react-dom@15.3.0/dist/react-dom.min.js"></script>
        <script src="https://npmcdn.com/babel-core@5.8.38/browser.min.js"></script>
        
        <script type="text/javascript" src="js/general.js"></script>
        
        
        -->
    </head>
    <body>
        <?php
        use Phalcon\Mvc\Model\Resultset\Simple as Resultset;
        
    	/*$usuario = $this->session->get("usuario");
		if($usuario != null && $usuario != ""){
			$this->session->set("error", "");
			$texto = armaMenu($usuario);
			$u = Usuario::findFirst($usuario);
			$p = Parametros::findFirst("parametro = 'initialPass'");
			if($p->valor != $u->clave){
				echo $texto;
			}
						
		}else{
			$homepage = "/comercial/";
			$currentpage = $_SERVER['REQUEST_URI'];
			$pos = strpos($currentpage, "retry");
			if($pos === false){
				if(!($homepage==$currentpage)) {
					$this->session->set("error", "Debe iniciar Sesi&oacute;n primero");
					header("Location: /comercial/");
				}else{
					$this->session->set("error", "");
				}	
			}							
		}
		
		function armaMenu($uid) {
			$user = Usuario::findFirst("id = $uid");
			$m = new Menu();
			$sql = "select * from menu where parent is null and id in (select x.menu from menu_x_rol x where x.rol = '".$user->rol_id."')";
			$titulos = new Resultset(null, $m, $m->getReadConnection()->query($sql));
			//$titulos = Menu::find(array("parent is null and id in (select x.menu from menu_x_rol x where x.rol = $user->rol_id)", "order" => "id"));
	    	$li1 = '<li class="pure-menu-item">';
	    	$lip = '<li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover pure-menu-link">';
	    	$a1 = '<a href="';
	    	$a2 = '" class="pure-menu-link">';
	    	$afin = '" class="custom-link-exit">';
	    	$lie = '</a></li>';
	    	$ul1 = '<ul class="pure-menu-children">';
	    	$ul2 = '</ul>';
	    	$html = '
	    	<div class="pure-menu pure-menu-horizontal">
			    <ul class="pure-menu-list">';
	    	foreach ($titulos as $t){
	    		$sm = new Menu();
	    		$sql2 = "select * from menu where parent = $t->id and id in (select x.menu from menu_x_rol x where x.rol = '".$user->rol_id."')";
	    		$smenus = new Resultset(null, $sm, $sm->getReadConnection()->query($sql2));
	    		//$smenus = Menu::find(array("parent = $t->id  and id in (select x.menu from menu_x_rol x where x.rol = $user->rol_id)", "order" => "id"));
	    		if(count($smenus) > 0){
	    			$html = $html.$lip.$t->label.$ul1;
	    			foreach ($smenus as $sm){
	    				$html = $html.$li1.$a1.$sm->href.$a2.$sm->label.$lie;
	    			}
	    			$html = $html.$ul2;
	    		}else{
	    			if($t->id == 99){
	    				$html = $html.$li1.$a1.$t->href.$afin.$t->label.$lie;
	    			}else{
	    				$html = $html.$li1.$a1.$t->href.$a2.$t->label.$lie;
	    			}
	    		}    		
	    	}
	    	$html = $html.'</ul><div class="logoRight"><img alt="logo" src="images/logo.png"></div></div>';
	    	return $html;
	    }*/	 
		?>
    	<header class="site-header">
        <div class="top-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <div class="top-header-left">
                            <a href="#">Inscr&iacute;bete</a>
                            <a href="#">Ingresar</a>
                        </div> <!-- /.top-header-left -->
                    </div> <!-- /.col-md-6 -->
                    <div class="col-md-6 col-sm-6">
                        <div class="social-icons">
                            <ul>
                                <li><a href="#" class="fa fa-facebook"></a></li>
                                <!--<li><a href="#" class="fa fa-dribbble"></a></li>-->
                                <li><a href="#" class="fa fa-twitter"></a></li>
                                <li><a href="#" class="fa fa-linkedin"></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div> <!-- /.social-icons -->
                    </div> <!-- /.col-md-6 -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.top-header -->
        <div class="main-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-8">
                        <div class="logo">
                            <h1><a href="#">Online Mall</a></h1>
                        </div> <!-- /.logo -->
                    </div> <!-- /.col-md-4 -->
                    <div class="col-md-8 col-sm-6 col-xs-4">
                        <div class="main-menu">
                            <a href="#" class="toggle-menu">
                                <i class="fa fa-bars"></i>
                            </a>
                            <ul class="menu">
                                <li><a href="#">Inicio</a></li>
                                <li><a href="#">Tiendas</a></li>
                                <li><a href="#">Preguntas</a></li>
                                <li><a href="#">Políticas</a></li>
                                <li><a href="#">Acerca de</a></li>
                            </ul>
                        </div> <!-- /.main-menu -->
                    </div> <!-- /.col-md-8 -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.main-header -->        
        <div class="main-nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-7">
                        <div class="list-menu">
                            <ul>
                                <li><a href="./index">Inicio</a></li>
                                <li><a href="./destacados">Destacados</a></li>
                                <li><a href="./contactanos">Contactanos</a></li>
                            </ul>
                        </div> <!-- /.list-menu -->
                    </div> <!-- /.col-md-6 -->
                    <div class="col-md-6 col-sm-5">
                        <div class="notification">
                            <span>Notificaciones...</span>
                        </div>
                    </div> <!-- /.col-md-6 -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </div> <!-- /.main-nav -->
        </header> <!-- /.site-header -->
        
        <div>
            <?php echo $this->getContent();?>            
	</div>         
        
        <footer class="site-footer">
            <!--<div class="our-partner">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="customNavigation">
                                <a class="btn prev"><i class="fa fa-angle-left"></i></a>
                                <a class="btn prev"><i class="fa fa-angle-left"></i></a>
                                <a class="btn next"><i class="fa fa-angle-right"></i></a>
                            </div>
                            <div id="owl-demo" class="owl-carousel">
                                <div class="item"> 
                                    <a href="#"><img src="images/tm-170x80-1.jpg" alt=""></a>
                                    </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-2.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-1.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-2.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-1.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-2.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-1.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-2.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-1.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href="#"><img src="images/tm-170x80-2.jpg" alt=""></a>
                                </div>
                            </div> 
                        </div> 
                    </div> 
                </div>  -->
            </div>  /.our-partner -->
            <div class="main-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="footer-widget">
                                <h3 class="widget-title">Acerca de</h3>
                                Centro Comercial en l&iacute;nea creado en El Salvador y disponible para todos los que quieran crear sus propias tiendas de manera f&aacute;cil
                                <ul class="follow-us">
                                    <li><a href="#"><i class="fa fa-facebook"></i>Facebook</a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i>Twitter</a></li>
                                </ul> <!-- /.follow-us -->
                            </div> <!-- /.footer-widget -->
                        </div> <!-- /.col-md-3 -->
                        <div class="col-md-3">
                            <div class="footer-widget">
                                <h3 class="widget-title">¿Por qu&eacute; escogernos?</h3>
                                Esta es la forma m&aacute;s f&aacute;cil de iniciar tu negocio en l&iacute;nea.                                
                            </div> <!-- /.footer-widget -->
                        </div> <!-- /.col-md-3 -->
                        <div class="col-md-2">
                            <div class="footer-widget">
                                <h3 class="widget-title">Enlaces &uacute;tiles</h3>
                                <ul>
                                    <li><a href="#">Nuestro Mall</a></li>
                                    <li><a href="#">Tiendas</a></li>
                                    <li><a href="#">Concursos</a></li>
                                    <li><a href="#">Acerca de</a></li>
                                    <li><a href="#">Ayuda</a></li>
                                </ul>
                            </div> <!-- /.footer-widget -->
                        </div> <!-- /.col-md-2 -->
                        <div class="col-md-4">
                            <div class="footer-widget">
                                <h3 class="widget-title">Subscr&iacute;bete</h3>
                                <div class="newsletter">
                                    <form action="#" method="get">
                                        <p>Ingresa tu correo para recibir las mejores ofertas seleccionadas de distintas tiendas</p>
                                        <input type="text" title="Email" name="email" placeholder="Escribe aqu&iacute; tu correo">
                                        <input type="submit" class="s-button" value="Ingresar" name="Submit">
                                    </form>
                                </div> <!-- /.newsletter -->
                            </div> <!-- /.footer-widget -->
                        </div> <!-- /.col-md-4 -->
                    </div> <!-- /.row -->
                </div> <!-- /.container -->
            </div> <!-- /.main-footer -->
            <!-- <div class="bottom-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <p>Dise&ntilde;ado por Francisco Lozano</p>
                        </div> 
                    </div> 
                </div> 
            </div>  /.bottom-footer -->
        </footer>  <!-- /.site-footer -->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) 
        <script src="js/vendor/jquery-1.10.1.min.js"></script>
        https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
        
        js/vendor/jquery-1.10.1.min.js
        -->
        <script src="js/jquery.js"></script>
        <script>window.jQuery || document.write('<script src="js/jquery.js"><\/script>')</script>
        <script src="js/jquery.easing-1.3.js"></script>
        <script src="js/bootstrap.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>
        
        <!-- 
            DataTables <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        -->
        
        
        <!-- jQuery Mask -->
        <script type="text/javascript" language="javascript" src="js/jquery.mask.min.js"></script>
        
        <!-- jQuery DatePicker -->
        <script type="text/javascript" language="javascript" src="js/picker.js"></script>
        <script type="text/javascript" language="javascript" src="js/picker.date.js"></script>
        <script type="text/javascript" language="javascript" src="js/es_ES.js"></script>
        
        <!-- General 
        js/jquery.dataTables.min.js
        -->
        <script type="text/javascript" src="js/moment.min.js"></script>
        <script type="text/javascript" language="javascript" src="js/dropdown.js"></script>
                
        <script type="text/javascript">
            $(document).ready(function() {
                $('.date').mask('0000-00-00');
                $('.datepicker').pickadate({
                    selectYears: true,
                    selectMonths: true
                    });
                $('.money').mask("#,##0.00", {reverse: true});
                $('.email').mask("A", {
                    translation: {
                            "A": { pattern: /[\w@\-.+]/, recursive: true }
                    }
                });
            });
        </script>        
    </body>
</html>
