<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#productos').DataTable();	
		$('.edit').hide();	
                
	} );

	<?php //echo $this->view->js;?>
            
        
</script>
<div class="form">
<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
?>
</div>
<?php
echo $this->view->tabla;
?>