<script type="text/javascript" language="javascript" class="init">
	/*$(document).ready(function() {
		//$('#productos').DataTable();	
		$('.edit').hide();	
                var table = new DataTable("productos");
	} );
*/
	<?php //echo $this->view->js;?>
            
        var myTable = document.querySelector("#productos");
        var dataTable = new DataTable(myTable,{
        columns: [
        // Sort the second column in ascending order
        { select: 1, sort: "asc" },
        { select: 4, hidden: true}
        ]});
        alert("dataTable fue llenada");
</script>

<?php 
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->botones;
echo $this->view->tabla;
?>

<style>    
a,
a:hover,
a:focus,
a:active {
	color: #333;
	outline: medium none;
	text-decoration: none;
}

.btn.active.focus,
.btn.active:focus,
.btn.focus,
.btn.focus:active,
.btn:active:focus,
.btn:focus {
	outline: medium none;
}

#ribbon {
	background: #fff none repeat scroll 0 0;
	box-shadow: 0 0 10px 0 rgba(0,0,0,0.1);
	font-weight: 400;
	padding: 15px;
	position: fixed;
	right: -269px;
	text-align: center;
	top: -125px;
	transform: rotate(45deg);
	transform-origin: 0 0 0;
	width: 500px;
	
	i {
		font-size: 21px;
		padding-right: 5px;
		vertical-align: middle;
	}
}


.dataTable-sorter::before {
    bottom: 8px;
}
.dataTable-sorter::after {
    top: 8px;
}

.selected {
	td {
		background-color: #27ae60;
		color: #fff;
	}
}
</style>